### ISSUE TITLE
serial baud rate

### ISSUE THREAD

**Issue by Xarin94** [Seithan/EasyNextionLibrary#12]
with this command the screen works but slowly, myNex.begin(9600)
i tried to write myNex.begin(115200);
but screen can' read anything.
thanks

**Comment by Seithan** [comment]
Hello,

This could be due to different baud rates. Arduino has 115200 and Nextion something else, possibly 9600.

In the Preinitialize Event of the first page loaded on Nextion, write: 
baud=115200 (this changes the baud rate of Nextion to 115200 only for that HMI file)
or
bauds=115200 (this changes the default baud rate to 115200)

Try to do this and let me know

**Comment by Xarin94** [comment]
thanks a lot, works
